modLoader="javafml"
loaderVersion="[31,)" 

[[mods]]
    modId="junglecreepermod"
    version="1.0.3"
    displayName="Jungle Creeper Mod"
	authors="Xrated_junior"
    description='''
    This mod adds a Jungle Creeper mob.
    '''
    
[[dependencies.junglecreepermod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"